# Generated by Django 5.1 on 2025-11-13 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('link_inscripcion', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FechaImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='historia/')),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fechas Importantes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('DIRECTOR', 'Director'), ('CODIRECTOR', 'Codirector'), ('INVESTIGADOR_S', 'Investigador Senior'), ('INVESTIGADOR_J', 'Investigador Junior'), ('TESISTA', 'Tesista'), ('ADMIN', 'Personal Administrativo')], max_length=30)),
                ('foto', models.ImageField(blank=True, default='default.jpg', upload_to='equipo/')),
                ('cargo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido', regex='^\\+?1?\\d{9,15}$')])),
                ('biografia', models.TextField()),
                ('linea_investigacion', models.CharField(max_length=200)),
                ('orcid_id', models.CharField(blank=True, max_length=50)),
                ('google_scholar', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('publicaciones_destacadas', models.TextField(blank=True, help_text='Una por línea')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Investigadores',
                'ordering': ['orden', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('equipamiento', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='laboratorios/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento'), ('PRENSA', 'Nota de Prensa')], max_length=50)),
                ('destacada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias y Eventos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autores', models.TextField(help_text='Separados por coma')),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ARTICULO', 'Artículo Científico'), ('CAPITULO', 'Capítulo de Libro'), ('CONFERENCIA', 'Conferencia'), ('PATENTE', 'Patente')], default='ARTICULO', max_length=20)),
                ('revista', models.CharField(blank=True, max_length=200)),
                ('doi', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('resumen', models.TextField(blank=True)),
                ('destacada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-año', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='servicios/')),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MISION', 'Misión'), ('VISION', 'Visión'), ('VALOR', 'Valor'), ('OBJETIVO', 'Objetivo')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(help_text='Ej: fa-dna, fa-microscope', max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_publica.investigador')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='web_publica.laboratorio')),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, upload_to='solicitudes/')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('PRESUPUESTO', 'En Presupuesto'), ('EJECUCION', 'En Ejecución'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='NUEVA', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_publica.servicio')),
            ],
        ),
    ]
