# Generated by Django 5.1 on 2025-11-13 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='categoria',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('INVESTIGADOR_S', 'Investigador Senior'), ('INVESTIGADOR_J', 'Investigador Junior'), ('BECARIO', 'Becario'), ('ADMIN', 'Personal Administrativo')], max_length=30),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('interno', 'Proyecto de Investigación'), ('colaborativo', 'Proyecto Colaborativo')], default='interno', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado')], default='PLANIFICACION', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='web_publica.investigador')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
