# Generated by Django 5.1 on 2025-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0002_alter_investigador_categoria_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('NOTICIA', 'Noticia'), ('PRENSA', 'Nota de Prensa')], max_length=50),
        ),
    ]
