# Generated by Django 5.1 on 2025-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0003_alter_noticia_options_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='linea_investigacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='publicaciones_destacadas',
            field=models.TextField(blank=True, help_text='Una por línea', null=True),
        ),
    ]
