# Generated by Django 5.1 on 2025-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0004_alter_investigador_biografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigador',
            old_name='cargo',
            new_name='titulo_Academico',
        ),
        migrations.AlterField(
            model_name='investigador',
            name='categoria',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('INVESTIGADOR', 'Investigador'), ('DOCENTE', 'Docente'), ('BECARIO', 'Becario'), ('ADMIN/TEC', 'Administrativo / Tecnico')], max_length=30),
        ),
    ]
