# Generated by Django 5.1 on 2025-11-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0005_rename_cargo_investigador_titulo_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
