# Generated by Django 5.1 on 2025-11-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0006_noticia_fecha_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_noticia'], 'verbose_name_plural': 'Noticias'},
        ),
    ]
