# Generated by Django 5.1 on 2025-11-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0007_alter_noticia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web_publica.noticia')),
            ],
        ),
    ]
