# Generated by Django 5.1 on 2025-11-15 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0008_noticiaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='enlace_prensa',
            field=models.URLField(blank=True, help_text='Link a nota original en medio de prensa'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='enlace_redes',
            field=models.URLField(blank=True, help_text='Link a publicación en redes sociales'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='keywords',
            field=models.CharField(blank=True, help_text='Palabras clave separadas por coma', max_length=255),
        ),
        migrations.AddField(
            model_name='noticia',
            name='lectura_estimada',
            field=models.PositiveIntegerField(default=5, help_text='Tiempo de lectura en minutos'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video',
            field=models.FileField(blank=True, help_text='Video opcional (MP4, máx 100MB)', null=True, upload_to='noticias/videos/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_url_externa',
            field=models.URLField(blank=True, help_text='URL de YouTube/Vimeo (alternativa a subir video)'),
        ),
        migrations.CreateModel(
            name='ComentarioNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tu nombre completo', max_length=100)),
                ('email', models.EmailField(help_text='No será publicado', max_length=254)),
                ('contenido', models.TextField(help_text='Máximo 500 caracteres', max_length=500)),
                ('aprobado', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='web_publica.noticia')),
            ],
            options={
                'verbose_name_plural': 'Comentarios de Noticias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='noticias/videos/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_extra', to='web_publica.noticia')),
            ],
        ),
    ]
