# Generated by Django 5.1 on 2025-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0009_noticia_enlace_prensa_noticia_enlace_redes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autores',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autores_externos',
            field=models.TextField(blank=True, help_text='Autores externos, separados por coma'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autores_investigadores',
            field=models.ManyToManyField(blank=True, related_name='publicaciones', to='web_publica.investigador'),
        ),
    ]
