# Generated by Django 5.1 on 2025-11-18 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0010_remove_publicacion_autores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios_a_cargo', to='web_publica.investigador'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='laboratorios_participantes', to='web_publica.investigador'),
        ),
        migrations.CreateModel(
            name='LaboratorioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='laboratorios/galeria/')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='web_publica.laboratorio')),
            ],
        ),
    ]
