# Generated by Django 5.1 on 2025-11-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0011_laboratorio_encargado_laboratorio_integrantes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='imagen',
            new_name='imagen_principal',
        ),
    ]
