# Generated by Django 5.1 on 2025-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0012_rename_imagen_laboratorio_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fuente',
            field=models.CharField(blank=True, choices=[('orcid', 'ORCID'), ('scholar', 'Google Scholar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
