# Generated by Django 5.1 on 2025-12-03 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0013_publicacion_fuente_alter_publicacion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='cvar_id',
            field=models.CharField(blank=True, help_text='CUIL o ID del CVAR', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BecaCVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('organismo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas_cvar', to='web_publica.investigador')),
            ],
        ),
        migrations.CreateModel(
            name='CargoCVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=255)),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_cvar', to='web_publica.investigador')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('rol', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('organismo', models.CharField(blank=True, max_length=255, null=True)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_cvar', to='web_publica.investigador')),
            ],
        ),
    ]
