# Generated by Django 5.1 on 2025-12-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0014_investigador_cvar_id_becacvar_cargocvar_proyectocvar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargocvar',
            name='investigador',
        ),
        migrations.RemoveField(
            model_name='proyectocvar',
            name='investigador',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='cvar_id',
        ),
        migrations.DeleteModel(
            name='BecaCVar',
        ),
        migrations.DeleteModel(
            name='CargoCVar',
        ),
        migrations.DeleteModel(
            name='ProyectoCVar',
        ),
    ]
