# Generated by Django 5.1 on 2025-12-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0015_remove_cargocvar_investigador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio_desde',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='laboratorios_colaboradores', to='web_publica.proyecto'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='web_publica.servicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='proyectos_participantes', to='web_publica.investigador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='laboratorios',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asociados', to='web_publica.laboratorio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorio_del_servicio', to='web_publica.laboratorio'),
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='equipamiento',
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipamiento/')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='operativo', max_length=30)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='web_publica.laboratorio')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='equipamiento',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='web_publica.equipamiento'),
        ),
    ]
