# Generated by Django 5.1 on 2025-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0016_remove_servicio_precio_desde_laboratorio_proyectos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorioimagen',
            name='imagen',
            field=models.ImageField(upload_to='laboratorios/galeria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo',
            field=models.CharField(choices=[('ARTICULO', 'Artículo Científico'), ('CAPITULO', 'Capítulo de Libro'), ('CONFERENCIA', 'Conferencia'), ('PATENTE', 'Patente'), ('LIBRO', 'Libro'), ('REVIEW', 'Review'), ('TESIS', 'Tesis')], default='ARTICULO', max_length=20),
        ),
    ]
