# Generated by Django 5.1 on 2026-09-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0017_alter_laboratorioimagen_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('resumen_corto', models.CharField(help_text='Frase corta que aparece debajo del título en la tarjeta (2 líneas aprox).', max_length=200)),
                ('icono', models.CharField(help_text='Clase de FontAwesome, ej: fa-microchip, fa-brain, fa-hard-hat, fa-graduation-cap', max_length=50)),
                ('descripcion_completa', models.TextField(help_text='Contenido ampliado que se muestra en la pantalla de detalle del programa.')),
                ('imagen_banner', models.ImageField(blank=True, help_text='Imagen opcional para la cabecera de la pantalla de detalle.', upload_to='programas/')),
                ('resolucion', models.CharField(blank=True, help_text='Ej: Res. 167/2024 CD (opcional, referencia normativa del programa).', max_length=100)),
                ('orden', models.IntegerField(default=0, help_text='Controla el orden de las tarjetas en la home.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa de Investigación',
                'verbose_name_plural': 'Programas de Investigación',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
