# Generated by Django 5.1 on 2026-09-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0018_programainvestigacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programainvestigacion',
            name='puntos_clave',
            field=models.TextField(blank=True, help_text='Sub-áreas o ítems que abarca el programa. Uno por línea. Ej: Tecnología para diagnóstico'),
        ),
        migrations.AlterField(
            model_name='programainvestigacion',
            name='descripcion_completa',
            field=models.TextField(help_text='Párrafo introductorio del programa (lo que va arriba de la lista de puntos).'),
        ),
    ]
