# Generated by Django 5.1 on 2026-09-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0019_programainvestigacion_puntos_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='programa',
            field=models.ForeignKey(blank=True, help_text='Programa de Investigación al que pertenece este proyecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asociados', to='web_publica.programainvestigacion'),
        ),
    ]
