# Generated by Django 5.1 on 2026-09-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publica', '0020_proyecto_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codirector',
            field=models.ForeignKey(blank=True, help_text='Cotitular / Codirector del proyecto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_codirigidos', to='web_publica.investigador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='desafio',
            field=models.TextField(blank=True, help_text='El problema u oportunidad que motiva el proyecto.'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del proyecto.', upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impacto',
            field=models.TextField(blank=True, help_text='El resultado o beneficio concreto esperado.'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='innovacion',
            field=models.TextField(blank=True, help_text='Qué se hace de forma novedosa para resolverlo.'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_financiamiento',
            field=models.CharField(blank=True, choices=[('PIC_CICITCA', 'PIC - CICITCA'), ('PDTS', 'PDTS'), ('OTRO', 'Otro / Sin financiamiento externo')], max_length=20),
        ),
    ]
